# Generated by Django 3.1.2 on 2020-10-12 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='GraduationYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PROGRAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(default=None, max_length=11, null=True)),
                ('present_work', models.CharField(max_length=100)),
                ('present_work_org', models.CharField(max_length=250)),
                ('facebook', models.URLField(default=None, null=True)),
                ('linkedin', models.URLField(default=None, null=True)),
                ('junior_intraction', models.BooleanField(null=True)),
                ('picture', models.ImageField(default='', upload_to='alumni/images')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.branch')),
                ('owner', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alumni_bio', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.program')),
                ('year_of_graduation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni.graduationyear')),
            ],
        ),
    ]
