# Generated by Django 3.1.2 on 2021-06-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20210619_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='picture',
            field=models.ImageField(upload_to='alumni'),
        ),
    ]
