# Generated by Django 3.1.2 on 2021-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebration',
            name='pic',
            field=models.ImageField(null=True, upload_to='celebration_list'),
        ),
    ]
