# Generated by Django 3.1.2 on 2022-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration', '0002_celebration_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='picture',
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic1',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic2',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic3',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic4',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic5',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic6',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic7',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='pictures',
            name='pic8',
            field=models.URLField(default=None),
        ),
    ]
