# Generated by Django 3.1.2 on 2023-03-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebration', '0003_auto_20220820_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='pic1',
            field=models.ImageField(null=True, upload_to='celebration_list'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic2',
            field=models.ImageField(null=True, upload_to='celebration_list'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic3',
            field=models.ImageField(null=True, upload_to='celebration_list'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic4',
            field=models.ImageField(null=True, upload_to='celebration_list'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic5',
            field=models.ImageField(null=True, upload_to='celebration_list'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic6',
            field=models.ImageField(null=True, upload_to='celebration_list'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic7',
            field=models.ImageField(null=True, upload_to='celebration_list'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='pic8',
            field=models.ImageField(null=True, upload_to='celebration_list'),
        ),
    ]
