# Generated by Django 3.1.2 on 2021-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210520_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pic',
            field=models.ImageField(default='', upload_to=None),
        ),
    ]
