# Generated by Django 3.1.2 on 2021-05-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pic',
            field=models.ImageField(default='', height_field='team', upload_to=None),
        ),
    ]
