# Generated by Django 3.1.2 on 2021-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20210520_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='pic',
            field=models.ImageField(default='', upload_to='team'),
        ),
    ]
