# Generated by Django 3.1.2 on 2022-08-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_prevteam_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prevteam',
            old_name='linkeden',
            new_name='linkedin',
        ),
    ]
