# Generated by Django 3.1.2 on 2022-08-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20220824_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevteam',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year', to='team.year'),
        ),
    ]
