# Generated by Django 3.1.2 on 2021-06-17 18:07

from django.db import migrations, models
import django.db.models.deletion
import paperman.models


class Migration(migrations.Migration):

    dependencies = [
        ('paperman', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='paperman',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=paperman.models.Category),
        ),
        migrations.AddField(
            model_name='paperman',
            name='upload',
            field=models.FileField(default=None, null=True, upload_to='paperman'),
        ),
        migrations.AddField(
            model_name='paperman',
            name='year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='paperman.year'),
        ),
        migrations.AlterField(
            model_name='paperman',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=paperman.models.Course),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(max_length=256),
        ),
    ]
