# Generated by Django 3.1.2 on 2021-06-17 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperman', '0002_auto_20210617_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperman',
            name='course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='paperman.course'),
        ),
        migrations.AlterField(
            model_name='paperman',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
