# Generated by Django 3.1.2 on 2021-06-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paperman', '0003_auto_20210617_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperman',
            name='category',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='paperman.category'),
        ),
    ]
