# Generated by Django 3.1.2 on 2021-05-21 17:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='inplace')),
                ('intro', ckeditor.fields.RichTextField()),
                ('article', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
