# Generated by Django 3.1.2 on 2020-12-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0002_auto_20201213_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='picture',
            field=models.CharField(max_length=500),
        ),
    ]
