# Generated by Django 3.1.2 on 2022-02-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0003_auto_20201213_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='picture',
            field=models.ImageField(upload_to='bio'),
        ),
    ]
