# Generated by Django 3.1.2 on 2021-05-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inphase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='inphase')),
                ('pic', models.ImageField(default=True, upload_to='inphase')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
