# Generated by Django 3.1.2 on 2021-05-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inphase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inphase',
            name='created_at',
        ),
    ]
