# Generated by Django 3.1.2 on 2021-05-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inphase', '0002_remove_inphase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inphase',
            name='pic',
            field=models.ImageField(default='', upload_to='inphase'),
        ),
    ]
