# Generated by Django 3.1.2 on 2021-05-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inphase', '0003_auto_20210521_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='inphase',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
