# Generated by Django 3.1.2 on 2022-02-18 08:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
                ('pic', models.ImageField(upload_to='shop')),
                ('category', models.CharField(default='', max_length=200)),
                ('sub_category', models.CharField(max_length=200)),
            ],
        ),
    ]
