# Generated by Django 3.1.2 on 2022-02-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discounted_price',
            new_name='discount_price',
        ),
    ]
