# Generated by Django 3.2.4 on 2021-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('roll_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
