# Generated by Django 3.1.2 on 2022-02-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('branch', models.IntegerField(default=0)),
                ('mon_8_9', models.CharField(blank=True, default='', max_length=41)),
                ('mon_9_10', models.CharField(blank=True, default='', max_length=41)),
                ('mon_10_11', models.CharField(blank=True, default='', max_length=41)),
                ('mon_11_12', models.CharField(blank=True, default='', max_length=41)),
                ('mon_12_1', models.CharField(blank=True, default='', max_length=41)),
                ('mon_2_3', models.CharField(blank=True, default='', max_length=41)),
                ('mon_3_4', models.CharField(blank=True, default='', max_length=41)),
                ('mon_4_5', models.CharField(blank=True, default='', max_length=41)),
                ('tue_8_9', models.CharField(blank=True, default='', max_length=41)),
                ('tue_9_10', models.CharField(blank=True, default='', max_length=41)),
                ('tue_10_11', models.CharField(blank=True, default='', max_length=41)),
                ('tue_11_12', models.CharField(blank=True, default='', max_length=41)),
                ('tue_12_1', models.CharField(blank=True, default='', max_length=41)),
                ('tue_2_3', models.CharField(blank=True, default='', max_length=41)),
                ('tue_3_4', models.CharField(blank=True, default='', max_length=41)),
                ('tue_4_5', models.CharField(blank=True, default='', max_length=41)),
                ('wed_8_9', models.CharField(blank=True, default='', max_length=41)),
                ('wed_9_10', models.CharField(blank=True, default='', max_length=41)),
                ('wed_10_11', models.CharField(blank=True, default='', max_length=41)),
                ('wed_11_12', models.CharField(blank=True, default='', max_length=41)),
                ('wed_12_1', models.CharField(blank=True, default='', max_length=41)),
                ('wed_2_3', models.CharField(blank=True, default='', max_length=41)),
                ('wed_3_4', models.CharField(blank=True, default='', max_length=41)),
                ('wed_4_5', models.CharField(blank=True, default='', max_length=41)),
                ('thur_8_9', models.CharField(blank=True, default='', max_length=41)),
                ('thur_9_10', models.CharField(blank=True, default='', max_length=41)),
                ('thur_10_11', models.CharField(blank=True, default='', max_length=41)),
                ('thur_11_12', models.CharField(blank=True, default='', max_length=41)),
                ('thur_12_1', models.CharField(blank=True, default='', max_length=41)),
                ('thur_2_3', models.CharField(blank=True, default='', max_length=41)),
                ('thur_3_4', models.CharField(blank=True, default='', max_length=41)),
                ('thur_4_5', models.CharField(blank=True, default='', max_length=41)),
                ('fri_8_9', models.CharField(blank=True, default='', max_length=41)),
                ('fri_9_10', models.CharField(blank=True, default='', max_length=41)),
                ('fri_10_11', models.CharField(blank=True, default='', max_length=41)),
                ('fri_11_12', models.CharField(blank=True, default='', max_length=41)),
                ('fri_12_1', models.CharField(blank=True, default='', max_length=41)),
                ('fri_2_3', models.CharField(blank=True, default='', max_length=41)),
                ('fri_3_4', models.CharField(blank=True, default='', max_length=41)),
                ('fri_4_5', models.CharField(blank=True, default='', max_length=41)),
            ],
        ),
    ]
