# Generated by Django 3.1.2 on 2022-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20220217_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='roll_number',
            new_name='year',
        ),
        migrations.AddField(
            model_name='timetable',
            name='branch',
            field=models.IntegerField(default=0),
        ),
    ]
