# Generated by Django 3.1.2 on 2022-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20210903_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='branch',
            field=models.IntegerField(default=0),
        ),
    ]
