# Generated by Django 3.1.2 on 2022-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_timetable_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='roll_number',
            field=models.IntegerField(default=True, primary_key=True, serialize=False),
        ),
    ]
