# Generated by Django 3.1.2 on 2022-02-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20220217_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='roll_number',
            field=models.IntegerField(default=18, primary_key=True, serialize=False),
        ),
    ]
