# Generated by Django 3.1.2 on 2022-02-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_auto_20220217_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='roll_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
