# Generated by Django 3.1.2 on 2022-02-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_auto_20220217_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='year',
        ),
    ]
