# Generated by Django 3.1.2 on 2022-08-08 18:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bios', '0004_auto_20220219_1944'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cpi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eligible_branch', models.ManyToManyField(to='bios.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RoundType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experince1', ckeditor.fields.RichTextField()),
                ('experince2', ckeditor.fields.RichTextField()),
                ('experince3', ckeditor.fields.RichTextField()),
                ('experince4', ckeditor.fields.RichTextField()),
                ('experince5', ckeditor.fields.RichTextField()),
                ('experince6', ckeditor.fields.RichTextField()),
                ('experince7', ckeditor.fields.RichTextField()),
                ('experince8', ckeditor.fields.RichTextField()),
                ('selected', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inplex.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inplex.profile')),
                ('roundtype1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one', to='inplex.roundtype')),
                ('roundtype2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two', to='inplex.roundtype')),
                ('roundtype3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three', to='inplex.roundtype')),
                ('roundtype4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four', to='inplex.roundtype')),
                ('roundtype5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five', to='inplex.roundtype')),
                ('roundtype6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six', to='inplex.roundtype')),
                ('roundtype7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven', to='inplex.roundtype')),
                ('roundtype8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eight', to='inplex.roundtype')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bios.year')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.ManyToManyField(to='inplex.Profile'),
        ),
    ]
