# Generated by Django 3.1.2 on 2022-08-09 06:58

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0004_auto_20220219_1944'),
        ('inplex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('linked_profile', models.URLField()),
                ('resource', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('resume', models.URLField(blank=True, null=True)),
                ('number', models.CharField(default=None, max_length=11, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.branch')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inplex.profile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.program')),
                ('selected_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inplex.company')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bios.year')),
            ],
        ),
        migrations.RenameModel(
            old_name='Selected',
            new_name='Difficulty',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='experince8',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='roundtype8',
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one', to='inplex.difficulty'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='two', to='inplex.difficulty'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='three', to='inplex.difficulty'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='four', to='inplex.difficulty'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='five', to='inplex.difficulty'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='six', to='inplex.difficulty'),
        ),
        migrations.AddField(
            model_name='experience',
            name='difficulty7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seven', to='inplex.difficulty'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experince1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experince2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experince3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experince4',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experince5',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experince6',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='experince7',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
