# Generated by Django 3.1.2 on 2022-08-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inplex', '0002_auto_20220809_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stipend',
            field=models.CharField(default=0, max_length=256),
        ),
    ]
