# Generated by Django 3.1.2 on 2022-08-20 06:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inplex', '0002_auto_20220809_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='difficulty1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='resource',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
