# Generated by Django 3.1.2 on 2022-08-20 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inplex', '0003_auto_20220820_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='difficulty1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one', to='inplex.difficulty'),
        ),
    ]
