# Generated by Django 3.1.2 on 2022-08-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inplex', '0009_auto_20220820_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='experince1',
            new_name='experience1',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='experince2',
            new_name='experience2',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='experince3',
            new_name='experience3',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='experince4',
            new_name='experience4',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='experince5',
            new_name='experience5',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='experince6',
            new_name='experience6',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='experince7',
            new_name='experience7',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='linked_profile',
            new_name='linked_in_profile',
        ),
    ]
